### ISSUE TITLE
dcm2jpg fails with java.lang.IllegalArgumentException: stream does not implement BytesWithImageImageDescriptor!

### ISSUE THREAD

**Issue by gunterze** [dcm4che/dcm4che#357]
If [ImageIO.getImageWritersByFormatName("jpeg")](https://docs.oracle.com/javase/8/docs/api/javax/imageio/ImageIO.html#getImageReadersByFormatName-java.lang.String-) returns an instance of `org.dcm4che3.opencv.NativeJPEGImageWriter` - and not an instance of `com.sun.imageio.plugins.jpeg.ImageWriter` -  writing the JPEG fails with 
```
Caused by: java.lang.IllegalArgumentException: stream does not implement BytesWithImageImageDescriptor!
        at org.dcm4che3.opencv.NativeJPEGImageWriter.write(NativeJPEGImageWriter.java:101)
```

Introduced by #340

Fix: Do **not** register `org.dcm4che3.opencv.NativeJPEGImageWriter` for format `jpeg`, and also not for mime type `image/jpeg`, because it does not support writing to a  `javax.imageio.stream.ImageOutputStream` which is not an instance of `org.dcm4che3.imageio.codec.BytesWithImageImageDescriptor`.
