### ISSUE TITLE
Utilities: Replace log4j-1.2.17 by logback-classic-1.2.9

### ISSUE THREAD

**Issue by richterjens** [dcm4che/dcm4che#1050]
The version of log4j that is used is labeled as end of life. 
It is also flagged during our vulnerability scans. 

Suggest to update to the latest release of log4j v2.14.1

**Comment by muralibarla** [comment]
`log4j:log4j:1.2.17` flagged during our vulnerability scan and this version is labeled as end of life.

Please update to `org.apache.logging.log4j:log4j:2.14.1`

**Comment by denicaM** [comment]
Same problem, It would be great if log4j is updated.

**Comment by chming1016** [comment]
As CVE-2021-44228 has Critical security issue and affects log4j >= 2.0.0, < 2.15.0, it is better to use 2.15.0 instead of 2.14.1.

**Comment by zooozoo** [comment]
Any plan for this update...?

**Comment by chming1016** [comment]
Hi

It seems like log4j 1.x is vulnerable to CVE-2021-44228. 

`
Update (2021-12-12 10:09 JST): according to this analysis by @TopStreamsNet, strictly speaking, applications using Log4j 1.x may be impacted if their configuration uses JNDI. However, the risk is much lower.
`

For detailed context, see [https://github.com/apache/logging-log4j2/pull/608#issuecomment-990494126](https://github.com/apache/logging-log4j2/pull/608#issuecomment-990494126)

Is dcm4che exploitable? or just vulnerable only? Thanks.

**Comment by jssuttles** [comment]
Sorry about this @gunterze, I know you're probably very busy, but will this be addressed soon?

**Comment by nroduit** [comment]
The dcm4che toolkit uses the sl4j facade and log4j 1.2.17 by default.

log4j 1.x is not affected by CVE-2021-44228, see [the analysis of the designer of log4j and sl4j](http://www.slf4j.org/log4shell.html). Note that the default logger configuration in dcm4che does not contain JMSAppender, so is not affected by the vulnerability CVE-2021-4104.

If you integrate dcm4che in third-party software then you have to check what is the logger (as it can be modified) and its configuration.

**Comment by gunterze** [comment]
Particular,y the library does **not** use any default, only the launcher scripts for the utilities currently includes `log4j-1.2.17.jar` with `slf4j-log4j12-1.7.30.jar` into the CLASSPATH. I will take a look to switch the utilities to use  [logback-classic](http://logback.qos.ch/)  by provided launchers.

**Comment by nroduit** [comment]
Yes it seems the best option to [move to logback 1.2.9](http://logback.qos.ch/news.html)

**Comment by sblour** [comment]
I am using dcm4che-net-2.0.29.jar that uses log4j. What is the replacement? I tried the newer versions of dcm4che-net, but it seems still uses log4j.
How to do this?

**Comment by gunterze** [comment]
I do not longer maintain dcm4che-2.x.
dcm4che-2.x - as dcm4che-3/5.x - depends on SLF4J, and **not** on log4j. So you may switch to using logback-classic without changing any source code  as done here for dcm4che-3/5.x.

**Comment by sblour** [comment]
We have switched to logback-classic, but in runtime the application fails on dcm4che.data that requires log4j.
Where I can retrieve jar files for dcm4che utility?

**Comment by sblour** [comment]
I am working on migrating to 5.25.1 now, after I downloaded zip file: dcm4che-5.25.1-bin\dcm4che-5.25.1\lib, I don't find dcm4che-dict jar, but there is dcm4che-dict-priv jar
where I can download dictionary file?

**Comment by sblour** [comment]
Can someone tells me the pom or maven link to download dcm4che 5.xx jars?

**Comment by sblour** [comment]
I am stuck here, does anyone have a solution?
Using dropwizard 2.0.28
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
